In [90]:
import requests
import nba_api
import pandas as pl
import io

In [91]:
from nba_api.stats.endpoints import *

In [100]:
player2 = commonallplayers.CommonAllPlayers()
player2_dict = player2.get_dict()

In [101]:
player2_resultSets = player2_dict['resultSets']
player2_dict_resultSets = player2_resultSets[0]
player2_headers_resultSets = player2_dict_resultSets['headers']
player2_rowSet_resultSets = player2_dict_resultSets['rowSet']

In [102]:
lf_player2 = pl.DataFrame(player2_rowSet_resultSets, columns = player2_headers_resultSets)

In [106]:
display(lf_player2.filter(pl.col('DISPLAY_FIRST_LAST').str.contains('Jokic')))

TypeError: boolean value of an expression is ambiguous

In [92]:
player = playerindex.PlayerIndex()
player_dict = player.get_dict()

In [93]:
player_resultSets = player_dict['resultSets']
player_dict_resultSets = player_resultSets[0]
player_headers_resultSets = player_dict_resultSets['headers']
player_rowSet_resultSets = player_dict_resultSets['rowSet']

In [94]:
lf_player = pl.DataFrame(player_rowSet_resultSets, columns = player_headers_resultSets)

In [97]:
display(lf_player)

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_ID,TEAM_SLUG,IS_DEFUNCT,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,...,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME,SUPPLEMENTAL_STATUS
0,1630173,Achiuwa,Precious,precious-achiuwa,1610612758,kings,0,Sacramento,Kings,SAC,...,1.0,20.0,1.0,2020,2026,10.1,6.7,1.4,Season,0
1,203500,Adams,Steven,steven-adams,1610612745,rockets,0,Houston,Rockets,HOU,...,1.0,12.0,1.0,2013,2026,5.8,8.6,1.5,Season,0
2,1628389,Adebayo,Bam,bam-adebayo,1610612748,heat,0,Miami,Heat,MIA,...,1.0,14.0,1.0,2017,2026,20.1,10.0,3.2,Season,0
3,1630534,Agbaji,Ochai,ochai-agbaji,1610612751,nets,0,Brooklyn,Nets,BKN,...,1.0,14.0,1.0,2022,2025,5.1,2.3,0.8,Season,0
4,1630583,Aldama,Santi,santi-aldama,1610612763,grizzlies,0,Memphis,Grizzlies,MEM,...,1.0,30.0,1.0,2021,2026,14.0,6.7,2.9,Season,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,1642959,Youngblood,Chris,chris-youngblood,1610612757,blazers,0,Portland,Trail Blazers,POR,...,NaN,NaN,1.0,2025,2026,2.1,0.8,0.4,Season,1
578,1630209,Yurtseven,Omer,omer-yurtseven,0,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,2020,2025,3.8,3.3,0.9,Season,0
579,1642911,Zikarsky,Rocco,rocco-zikarsky,1610612750,timberwolves,0,Minnesota,Timberwolves,MIN,...,2.0,45.0,1.0,2025,2026,2.8,2.8,0.4,Season,1
580,1627826,Zubac,Ivica,ivica-zubac,1610612754,pacers,0,Indiana,Pacers,IND,...,2.0,32.0,1.0,2016,2026,14.1,10.6,2.2,Season,0
581,1641783,da Silva,Tristan,tristan-da-silva,1610612753,magic,0,Orlando,Magic,ORL,...,1.0,18.0,1.0,2024,2026,9.9,3.7,1.6,Season,0

In [96]:
display(lf_player.filter(pl.col('PLAYER_FIRST_NAME') == 'Lebron'))

TypeError: boolean value of an expression is ambiguous

In [ ]:
player_carrer = playercareerstats.PlayerCareerStats(player_id='203999')
player_carrer_dict = player_carrer.get_dict()

In [ ]:
resultSets = player_carrer_dict['resultSets']
dict_reslultSets = resultSets[0]
headers_resultSets = dict_reslultSets['headers']
rowSet_resultSets = dict_reslultSets['rowSet']

In [69]:
lf = pl.DataFrame(rowSet_resultSets, columns = headers_resultSets)

In [71]:
display(lf)

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,69,69,2323,646,...,0.822,167,650,817,678,87,47,247,174,1690
8,203999,2023-24,00,1610612743,DEN,29.0,79,79,2737,822,...,0.817,223,753,976,708,108,68,237,194,2085
9,203999,2024-25,00,1610612743,DEN,30.0,70,70,2571,786,...,0.800,200,692,892,716,127,45,230,160,2071
10,203999,2025-26,00,1610612743,DEN,31.0,65,65,2265,644,...,0.831,192,644,836,697,92,53,243,173,1799